#FROM gcr.io/google_containers/exechealthz-amd64:v1.2.0
#FROM gcr.io/google_containers/exechealthz-amd64:v1.2
#Modify the image tag 1.2
FROM gcr.io/google_containers/exechealthz-amd64:1.2
MAINTAINER kenzhaoyihui <kenzhaoyihui@kenzhaoyihui.me>
